# frozen_string_literal: true

# Build-time rendering of TikZ pictures to static SVG.
#
# Markdown sources embed diagrams exactly as TikZJax expects them:
#
#   <script type="text/tikz">
#     \begin{tikzpicture} ... \end{tikzpicture}
#   </script>
#
# but instead of shipping a WebAssembly TeX engine to the reader, each block is
# compiled here with latex + dvisvgm and replaced by an <img> pointing at a
# static SVG under assets/img/tikz/.
#
# SVGs are cached by a hash of their own source, so a diagram is only compiled
# when it is new or has been edited. The cache is committed to the repository
# so most builds find every SVG already present; CI installs TeX too, so a
# diagram whose SVG was not committed is rendered there instead. Run
# bin/render-tikz on a machine with TeX to populate the cache locally.
#
# This file is loaded both by Jekyll (as a plugin) and by bin/render-tikz (as a
# plain library), so everything outside the `defined?(Jekyll)` guard at the
# bottom must stay free of Jekyll dependencies -- and Ruby 2.6 compatible,
# since the host TeX machine may be running the system Ruby.

require "digest"
require "fileutils"
require "open3"
require "tmpdir"

module TikzRender
  CACHE_DIR = File.join("assets", "img", "tikz")

  # Scale factor applied by dvisvgm. TeX's natural sizing is tuned for print and
  # comes out noticeably small on screen.
  ZOOM = 1.5

  # Bump to invalidate every cached SVG, e.g. after changing the preamble below.
  PREAMBLE_VERSION = 1

  # Matches a <script type="text/tikz"> block, capturing its attributes and body.
  SCRIPT_RE = %r{<script\b([^>]*?\btype\s*=\s*(["'])text/tikz\2[^>]*?)>(.*?)</script>}m

  LIBRARY_RE = /^[ \t]*\\usetikzlibrary\{[^}]*\}[ \t]*$/
  PACKAGE_RE = /^[ \t]*\\usepackage(?:\[[^\]]*\])?\{[^}]*\}[ \t]*$/

  class CompileError < StandardError; end

  module_function

  # Identifies a diagram by its source, so editing a diagram yields a new file
  # and stale ones become detectable.
  def cache_key(source)
    Digest::SHA256.hexdigest(
      [PREAMBLE_VERSION.to_s, ZOOM.to_s, source.strip].join("\x00")
    )[0, 16]
  end

  def svg_relative_path(key)
    File.join(CACHE_DIR, "#{key}.svg")
  end

  def svg_absolute_path(key, root)
    File.join(root, svg_relative_path(key))
  end

  # True when this machine can actually compile TikZ.
  def toolchain_available?
    return @toolchain_available unless @toolchain_available.nil?
    @toolchain_available = %w[latex dvisvgm].all? do |tool|
      system("command -v #{tool} > /dev/null 2>&1")
    end
  end

  # Builds a standalone document from a snippet, hoisting any \usepackage and
  # \usetikzlibrary lines out of the body and into the preamble where they belong.
  def build_document(source)
    libraries = source.scan(LIBRARY_RE).map(&:strip)
    packages = source.scan(PACKAGE_RE).map(&:strip)
    body = source.gsub(LIBRARY_RE, "").gsub(PACKAGE_RE, "").strip

    <<~TEX
      \\documentclass[dvisvgm,border=2pt]{standalone}
      \\usepackage{tikz}
      #{packages.join("\n")}
      #{libraries.join("\n")}
      \\begin{document}
      #{body}
      \\end{document}
    TEX
  end

  # Compiles a snippet and returns the SVG as a string. Raises CompileError with
  # the relevant part of the TeX log when the diagram does not build.
  def compile(source)
    unless toolchain_available?
      raise CompileError, "latex and dvisvgm are required to render TikZ diagrams"
    end

    Dir.mktmpdir("tikz") do |dir|
      tex = File.join(dir, "diagram.tex")
      File.write(tex, build_document(source))

      out, _status = Open3.capture2e(
        "latex", "-interaction=nonstopmode", "-halt-on-error",
        "-output-directory=#{dir}", tex
      )
      dvi = File.join(dir, "diagram.dvi")
      unless File.exist?(dvi)
        raise CompileError, "latex failed:\n#{tex_errors(out)}"
      end

      svg = File.join(dir, "diagram.svg")
      out, _status = Open3.capture2e(
        "dvisvgm", "--no-fonts", "--exact-bbox", "--optimize=all",
        "--zoom=#{ZOOM}", "--output=#{svg}", dvi
      )
      unless File.exist?(svg)
        raise CompileError, "dvisvgm failed:\n#{out}"
      end

      normalise(File.read(svg))
    end
  end

  # dvisvgm stamps its own version into a comment, which is the only thing that
  # differs between rendering on, say, MacTeX and the Docker image. Dropping it
  # makes the cached SVGs byte-identical whoever builds them, so switching
  # machines does not produce a diff in every diagram.
  def normalise(svg)
    svg.sub(/^<!-- This file was generated by dvisvgm [^>]*-->\n/, "")
  end

  # Pulls the interesting lines out of a TeX log; the full log is mostly noise.
  def tex_errors(log)
    lines = log.lines.select { |l| l.start_with?("!") || l =~ /^l\.\d+/ }
    lines = log.lines.last(15) if lines.empty?
    lines.join.strip
  end

  # Renders a diagram to the cache if it is not already there. Returns the key.
  def ensure_svg(source, root, force = false)
    key = cache_key(source)
    path = svg_absolute_path(key, root)
    return key if File.exist?(path) && !force

    svg = compile(source)
    FileUtils.mkdir_p(File.dirname(path))
    File.write(path, svg)
    key
  end

  # dvisvgm reports the drawing's size in TeX points; browsers want px, and
  # supplying both stops the page reflowing as diagrams load.
  def pixel_dimensions(svg)
    match = svg.match(/<svg[^>]*?\bwidth=['"]([\d.]+)pt['"][^>]*?\bheight=['"]([\d.]+)pt['"]/)
    return nil unless match
    [(match[1].to_f * 4.0 / 3.0).round, (match[2].to_f * 4.0 / 3.0).round]
  end

  # Extracts alt="..." from the script tag's attributes, so diagrams can carry
  # a real description rather than a generic one.
  def alt_text(attributes)
    match = attributes.match(/\balt\s*=\s*(["'])(.*?)\1/m)
    match ? match[2] : "TikZ diagram"
  end

  def escape_html(text)
    text.gsub("&", "&amp;").gsub("<", "&lt;").gsub(">", "&gt;").gsub('"', "&quot;")
  end

  # Finds every diagram in a page of markdown/HTML. Returns the raw sources.
  def extract_sources(content)
    content.scan(SCRIPT_RE).map { |_attrs, _quote, body| body }
  end

  # Removes fenced blocks and inline code spans. Scanning raw markdown would
  # otherwise treat a <script type="text/tikz"> quoted in prose -- as a post
  # explaining this very feature is bound to do -- as the start of a diagram.
  # Only needed for markdown; by the time Jekyll renders HTML such a mention has
  # been escaped to &lt;script and no longer matches.
  def strip_code_regions(content)
    without_fences = content.gsub(/^[ \t]*(`{3,}|~{3,})[^\n]*\n.*?^[ \t]*\1[ \t]*$/m, "")
    without_fences.gsub(/(`+)(?:(?!\1)[\s\S])*\1/, "")
  end

  def img_tag(key, alt, dimensions, url_prefix)
    size = dimensions ? %( width="#{dimensions[0]}" height="#{dimensions[1]}") : ""
    src = "#{url_prefix}/#{svg_relative_path(key)}"
    %(<figure class="tikz"><img src="#{src}" alt="#{escape_html(alt)}"#{size} loading="lazy"></figure>)
  end
end

if defined?(Jekyll)
  module TikzRender
    # Tracks SVGs added mid-build so each is only registered with Jekyll once.
    def self.registered
      @registered ||= {}
    end

    # A file created during rendering is not in site.static_files (the read phase
    # is long over), so Jekyll would neither copy it nor protect it from the
    # cleaner. Registering it here fixes both.
    def self.register_static_file(site, key)
      return if registered[key]
      registered[key] = true
      site.static_files << Jekyll::StaticFile.new(
        site, site.source, CACHE_DIR, "#{key}.svg"
      )
    end

    def self.substitute(content, site)
      content.gsub(SCRIPT_RE) do
        attributes = Regexp.last_match(1)
        source = Regexp.last_match(3)
        render_one(source, attributes, site) || Regexp.last_match(0)
      end
    end

    def self.render_one(source, attributes, site)
      key = cache_key(source)
      path = svg_absolute_path(key, site.source)

      unless File.exist?(path)
        if toolchain_available?
          begin
            ensure_svg(source, site.source)
          rescue CompileError => e
            return failure(site, "TikZ diagram failed to compile:\n#{e.message}")
          end
        else
          return failure(
            site,
            "No SVG cached for a TikZ diagram (expected #{svg_relative_path(key)}) " \
            "and no TeX toolchain available to build one. Run bin/render-tikz on a " \
            "machine with latex and dvisvgm, and commit the result."
          )
        end
        register_static_file(site, key)
      end

      img_tag(key, alt_text(attributes), pixel_dimensions(File.read(path)), site.baseurl.to_s)
    end

    # A missing diagram is a broken page. Fail the build in production rather
    # than publishing a post with a hole in it; in development show the problem
    # in place so it is obvious while writing.
    def self.failure(site, message)
      if Jekyll.env == "production"
        raise message
      end
      Jekyll.logger.warn "TikZ:", message
      %(<figure class="tikz tikz-error"><pre>#{escape_html(message)}</pre></figure>)
    end
  end

  Jekyll::Hooks.register %i[posts pages documents], :post_render do |doc|
    output = doc.output
    next unless output.is_a?(String) && output.include?("text/tikz")
    doc.output = TikzRender.substitute(output, doc.site)
  end
end
